apiVersion: v1
kind: Service
metadata:
  name: upgrade-planner-plugin
  namespace: openshift-console
  labels:
    app: upgrade-planner-plugin
    app.kubernetes.io/name: upgrade-planner-plugin
    app.kubernetes.io/component: dynamic-plugin
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: upgrade-planner-plugin-cert
spec:
  type: ClusterIP
  ports:
    - name: backend
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: frontend
      port: 9443
      targetPort: 9443
      protocol: TCP
  selector:
    app: upgrade-planner-plugin
